#!/bin/bash

echo "============================================================"
echo "MCPR Example Testing Guide"
echo "============================================================"
echo ""
echo "This guide will help you test the MCPR example client and server."
echo ""
echo "1. First, test the client in test mode (no server connection):"
echo "   cd client && cargo run -- --test-mode"
echo ""
echo "2. To run the server:"
echo "   cd server && cargo run"
echo ""
echo "3. In a separate terminal, connect the client to the running server:"
echo "   cd client && cargo run -- --connect"
echo ""
echo "Notes:"
echo "- The server must be running before starting the client with --connect"
echo "- The server shuts down immediately when running on stdio"
echo "- Test mode verifies the client tool registration without connecting"
echo ""
echo "Try testing each component separately to verify functionality."
echo "============================================================" 